[package]
name = "pve-ssh"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
ctrlc = "3.4.5"
dialoguer = "0.11.0"
dirs = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
whoami = "1.5.2"
