name: pve-ssh build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build pve-ssh
        run: |
          cargo build --release -p pve-ssh
          strip target/release/pve-ssh
          mv target/release/pve-ssh target/release/pve-ssh_amd64

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/pve-ssh_amd64

  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build pve-ssh
        run: cargo build --release -p pve-ssh
        shell: powershell

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/pve-ssh.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build pve-ssh
        run: |
          cargo build --release -p pve-ssh
          strip target/release/pve-ssh
          mv target/release/pve-ssh target/release/pve-ssh_darwin

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/pve-ssh_darwin
